// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"editorconfig-guesser/internal/cli"
)

var _ Cmd = (*Generate)(nil)

type Generate struct {
	*RootCmd
	Flags         *flag.FlagSet
	saveFlag      bool
	verboseFlag   bool
	args          []string
	SubCommands   map[string]Cmd
	CommandAction func(c *Generate) error
}

type UsageDataGenerate struct {
	*Generate
	Recursive bool
}

func (c *Generate) Usage() {
	err := executeUsage(os.Stderr, "generate_usage.txt", UsageDataGenerate{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Generate) UsageRecursive() {
	err := executeUsage(os.Stderr, "generate_usage.txt", UsageDataGenerate{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Generate) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "saveFlag", "save", "s":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.saveFlag = b
				} else {
					c.saveFlag = true
				}

			case "verboseFlag", "verbose", "v":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.verboseFlag = b
				} else {
					c.verboseFlag = true
				}
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		} else {
			remainingArgs = append(remainingArgs, arg)
		}
	}
	// Handle vararg args
	{
		varArgStart := 0
		if varArgStart > len(remainingArgs) {
			varArgStart = len(remainingArgs)
		}
		varArgs := remainingArgs[varArgStart:]
		c.args = varArgs
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("generate failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewGenerate() *Generate {
	set := flag.NewFlagSet("generate", flag.ContinueOnError)
	v := &Generate{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.BoolVar(&v.saveFlag, "save", false, "Save the file as .editorconfig")
	set.BoolVar(&v.saveFlag, "s", false, "Save the file as .editorconfig")

	set.BoolVar(&v.verboseFlag, "verbose", false, "Logs more than what is required")
	set.BoolVar(&v.verboseFlag, "v", false, "Logs more than what is required")
	set.Usage = v.Usage

	v.CommandAction = func(c *Generate) error {

		cli.Generate(c.saveFlag, c.verboseFlag, c.args...)
		return nil
	}

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
