on: [push, pull_request]
name: Test
jobs:
    test:
        runs-on: windows-latest
        steps:
            - name: Install Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.23"
            - name: Cache-Go
              uses: actions/cache@v4
              with:
                path: |
                  ~/go/pkg/mod              # Module download cache
                  ~/.cache/go-build         # Build cache (Linux)
                  ~/Library/Caches/go-build # Build cache (Mac)
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                restore-keys: |
                  ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Test
              run: |
                go mod download
                go test ./...
